import '../../interfaces/screens/auth/lang/auth_pt_lang.dart';
import 'keys_lang.dart';

abstract class PtLang {
  static final words = <String, String>{
    KeysLang.tryAgain: 'Tentar novamente',
    KeysLang.appName: 'RecebiApp',
    KeysLang.home: 'Inicio',
    KeysLang.logout: 'Sair',
    KeysLang.appDescription: 'Melhor app para gerenciar pagamentos!',
    KeysLang.email: 'Email',
    KeysLang.password: 'Senha',
    KeysLang.back: 'Voltar',
    KeysLang.confirmPassword: 'Confirmar senha',
    KeysLang.name: 'Nome',
    KeysLang.requiredField: 'Campo obrigatório',
    KeysLang.invalidEmail: 'Email inválido',
    KeysLang.minLength: 'Minimo de {min} caracteres',
    KeysLang.passwordsDontMatch: 'Senhas não coincidem',
    KeysLang.or: 'ou',
    KeysLang.cancel: 'Cancelar',
    KeysLang.cancelPayment: 'Cancelar pagamento',
    KeysLang.uncancel: 'Desfazer cancelamento',
    KeysLang.confirm: 'Confirmar',
    KeysLang.delete: 'Excluir',
    KeysLang.themeMode: 'Aparência',
    KeysLang.darkMode: 'Modo Escuro',
    KeysLang.lightMode: 'Modo Claro',
    KeysLang.free: 'Plano gratuito',
    KeysLang.freeTrial: 'Plano premium teste',
    KeysLang.premiumMensal: 'Plano premium mensal',
    KeysLang.premiumManual: 'Plano premium anual',
    KeysLang.monetizationPage: 'Assinatura do app',
    KeysLang.customers: 'Clientes',
    KeysLang.supplier: 'Fornecedor',
    KeysLang.customer: 'Cliente',
    KeysLang.all: 'Todos',
    KeysLang.newData: 'Novo',
    KeysLang.editData: 'Editar',
    KeysLang.createdAt: 'Criado em',
    KeysLang.updatedAt: 'Atualizado em',
    KeysLang.income: 'Receita',
    KeysLang.expense: 'Despesa',
    KeysLang.pending: 'Pendente',
    KeysLang.paid: 'Pago',
    KeysLang.pay: 'Pagar',
    KeysLang.dueToday: 'Vencendo hoje',
    KeysLang.overdue: 'Atrasado',
    KeysLang.canceled: 'Cancelado',
    KeysLang.edit: 'Editar',
    KeysLang.interval: 'Intervalo',
    KeysLang.intervalDays: 'Intervalo em dias',
    KeysLang.monthly: 'Mensal',
    KeysLang.weekly: 'Semanal',
    KeysLang.dayOfMonth: 'Dia do mês',
    KeysLang.dayOfWeek: 'Dia da semana',
    KeysLang.monday: 'Segunda-feira',
    KeysLang.tuesday: 'Terça-feira',
    KeysLang.wednesday: 'Quarta-feira',
    KeysLang.thursday: 'Quinta-feira',
    KeysLang.friday: 'Sexta-feira',
    KeysLang.saturday: 'Sábado',
    KeysLang.sunday: 'Domingo',
  };

  static const wordsAuth = AuthPtLang;
}
