import '../../interfaces/screens/auth/lang/auth_us_lang.dart';
import 'keys_lang.dart';

abstract class UsLang {
  static final words = <String, String>{
    KeysLang.tryAgain: 'Try again',
    KeysLang.appName: 'ReceivedApp',
    KeysLang.home: 'Home',
    KeysLang.logout: 'Logout',
    KeysLang.appDescription: 'Best app for your receipts and payments!',
    KeysLang.email: 'Email',
    KeysLang.password: 'Password',
    KeysLang.back: 'Back',
    KeysLang.confirmPassword: 'Confirm Password',
    KeysLang.name: 'Name',
    KeysLang.requiredField: 'Required field',
    KeysLang.invalidEmail: 'Invalid email',
    KeysLang.minLength: 'Minimum of {min} characters',
    KeysLang.passwordsDontMatch: 'Passwords dont match',
    KeysLang.or: 'or',
    KeysLang.cancel: 'Cancel',
    KeysLang.confirm: 'Confirm',
    KeysLang.themeMode: 'Theme Mode',
    KeysLang.darkMode: 'Dark Mode',
    KeysLang.lightMode: 'Light Mode',
    KeysLang.free: 'Free plan',
    KeysLang.freeTrial: 'Free trial plan',
    KeysLang.premiumMensal: 'Premium monthly plan',
    KeysLang.premiumManual: 'Premium annual plan',
    KeysLang.monetizationPage: 'App subscription',
    KeysLang.customers: 'Customers',
    KeysLang.supplier: 'Supplier',
    KeysLang.customer: 'Customer',
    KeysLang.all: 'All',
    KeysLang.newData: 'New',
    KeysLang.editData: 'Edit',
    KeysLang.createdAt: 'Created at',
    KeysLang.updatedAt: 'Updated at',
    KeysLang.income: 'Income',
    KeysLang.expense: 'Expense',
    KeysLang.pending: 'Pending',
    KeysLang.paid: 'Paid',
    KeysLang.dueToday: 'Due today',
    KeysLang.overdue: 'Overdue',
    KeysLang.canceled: 'Canceled',
    KeysLang.edit: 'Edit',
  };

  static const wordsAuth = AuthUsLang;
}
